### ISSUE TITLE
Failing on start

### ISSUE THREAD

**Issue by Ark74** [sugarlabs/Measure#18]
Hello again, 
This is the last report from my crusade to review all the sugar activities bundled with trisquel-sugar.

I'm using what seems to be the 103 (master) version of the `measure` activity.

I'm not sure about this, but could the following error has something to do with the alsa package?

```
==> .sugar/default/logs/org.laptop.MeasureActivity-1.log <==
  File "/usr/lib/python3/dist-packages/sugar3/activity/activityinstance.py", line 230, in main
    instance = create_activity_instance(activity_constructor, activity_handle)
  File "/usr/lib/python3/dist-packages/sugar3/activity/activityinstance.py", line 59, in create_activity_instance
    activity = constructor(handle)
  File "/usr/share/sugar/activities/Measure.activity/measure.py", line 187, in __init__
    self.audiograb = ag(self.wave.new_buffer, self)
  File "/usr/share/sugar/activities/Measure.activity/audiograb.py", line 125, in __init__
    self.pipeline.add(self.alsasrc)
TypeError: Argument 1 does not allow None as a value
```

As before thanks in advance!

**Comment by quozl** [comment]
Verify that `gst-inspect alsasrc` returns good output.  if it says no such element or plugin, you need to install it.  In my own OLPC OS package of this activity, there is a dependency on 

```
debian/rules:CDBS_DEPENDS_$(pkg) +=, gir1.2-gstreamer-1.0, gir1.2-gst-plugins-base-1.0
debian/rules:CDBS_DEPENDS_$(pkg) +=, gstreamer1.0-plugins-good
debian/rules:CDBS_DEPENDS_$(pkg) +=, gstreamer1.0-alsa
```

**Comment by Ark74** [comment]
It was `gstreamer1.0-alsa` who did the trick.
Thank you very much.

**Comment by Ark74** [comment]
Again, thanks for all the help.

I thought you might like to see check the output we got with your help.
http://ark.switnet.org/tmp/nabia/trisquel-sugar/trisquel-sugar_10.0_amd64.iso

It should be available too at: http://cdbuilds.trisquel.org/nabia/ later.
Cheers!
