### ISSUE TITLE
Question mark missing

### ISSUE THREAD

**Issue by ujdhesa** [sugarlabs/Measure#4]
Hello,

It seems that there’s a question mark missing in this string:

_Do you want to downgrade to version %s_

Shouldn’t that be:

_Do you want to downgrade to version %s?_

**Comment by quozl** [comment]
There's no such string here in Measure.  Are you sure it is in Measure you saw this?

**Comment by ujdhesa** [comment]
My bad! I apologize for the mistake. I have mislabelled another file as measure.po…
