### ISSUE TITLE
Version Problem

### ISSUE THREAD

**Issue by tony37** [sugarlabs/Measure#6]
Version shown in ASLO is 52. An older version shows 53. The repository version is 100.

**Comment by quozl** [comment]
ASLO shows 53 to Browse when running Sugar 0.110, as it should.  Don't look at what other browsers show you on ASLO, as they will be affected by https://github.com/sugarlabs/aslo/issues/3

v100 is a port to GTK+ 3.0 and GStreamer 1.0; it is not yet released as a bundle, though it has been taken by OLPC as a package.
