### ISSUE TITLE
Fails on unknown architecture

### ISSUE THREAD

**Issue by tony37** [sugarlabs/Measure#7]
The activity (v100) throws an exception with the Ubuntu 16.04 sucrose version. 

measure.py @line 123:

    return model.split((' ')[0] 

AttributeError: 'Nonetype' object has no attribute 'split'.

This problem can be corrected by changing the line to:

if not model:
    return 'Unknown' 
else:
    return model.split('   ')[0]

**Comment by quozl** [comment]
It works fine for me on Ubuntu 16.04 with Sugar 0.110.

**Comment by quozl** [comment]
df99a3d284d8a0256dc0da32380e6d9bf1db9fa5
