### ISSUE TITLE
Gst.pipeline error in audiograb.py

### ISSUE THREAD

**Issue by walterbender** [sugarlabs/Measure#8]
I'm bumping into a problem with audiograb.py in sugar-build. The call to Gst.pipeline('pipeline') fails: init takes 0 args. But if you change the call to Gst.pupeline.new('pipeline') everything works as expected.

I am using an up-to-date sugar-build (refreshed from the master branch and Measure 101.

**Comment by quozl** [comment]
Thanks for the research.  Merged.

Side issue ... I've not been testing with sugar-build, but would like to know what version of GStreamer is reported;

```
$ python
>>> from gi.repository import Gst
>>> Gst.version()
```

as it won't necessarily be the same as your Fedora 24 host system.

And does Measure display the audio waveform at all?  It does not on Fedora 18, which is a different issue.
